repository:
  description: A template repository for testing purposes.

#branches:
  #owner: lauren-sergi
  #repo: template-repo
  branch: master
  required_status_checks: null
  enforce_admins: null
  required_pull_request_reviews:
    - require_code_owner_reviews: true
      required_approving_review_count: 1
  restrictions: null
